# Generated by Django 6.1 on 2026-08-19 14:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipecomment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=models.Index(fields=['author', '-created_at'], name='core_recipe_author__36ec2e_idx'),
        ),
        migrations.AddIndex(
            model_name='recipecomment',
            index=models.Index(fields=['recipe', '-created_at'], name='core_recipe_recipe__7e74a9_idx'),
        ),
        migrations.AddIndex(
            model_name='recipereview',
            index=models.Index(fields=['recipe', 'rating'], name='core_recipe_recipe__311c0f_idx'),
        ),
        migrations.AddIndex(
            model_name='shoppinglist',
            index=models.Index(fields=['user', '-created_at'], name='slist_user_created_idx'),
        ),
    ]
