# Generated by Django 6.1 on 2026-08-24 18:25

import core.utils.units
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='unit',
            field=models.CharField(blank=True, max_length=50, validators=[core.utils.units.validate_unit]),
        ),
        migrations.AlterField(
            model_name='shoppinglistitem',
            name='unit',
            field=models.CharField(blank=True, max_length=50, validators=[core.utils.units.validate_unit]),
        ),
    ]
